2020-01-10 10:16:33 WARNING    [utils.py:utils:376] Expired authorization token detected.
2020-01-10 10:16:33 WARNING    [utils.py:utils:402] Both authorization and refresh tokens are expired. Requesting new ones...
2020-01-10 10:16:33 INFO       [utils.py:utils:145] Requesting http://localhost:8080/api/auth/login...
2020-01-10 10:17:04 WARNING    [utils.py:utils:376] Expired authorization token detected.
2020-01-10 10:17:04 WARNING    [utils.py:utils:402] Both authorization and refresh tokens are expired. Requesting new ones...
2020-01-10 10:17:04 INFO       [utils.py:utils:145] Requesting http://localhost:8080/api/auth/login...
2020-01-10 13:30:28 WARNING    [utils.py:utils:376] Expired authorization token detected.
2020-01-10 13:30:28 WARNING    [utils.py:utils:402] Both authorization and refresh tokens are expired. Requesting new ones...
2020-01-10 13:30:28 INFO       [utils.py:utils:145] Requesting http://localhost:8080/api/auth/login...
2020-01-10 13:30:33 WARNING    [utils.py:utils:376] Expired authorization token detected.
2020-01-10 13:30:33 WARNING    [utils.py:utils:402] Both authorization and refresh tokens are expired. Requesting new ones...
2020-01-10 13:30:33 INFO       [utils.py:utils:145] Requesting http://localhost:8080/api/auth/login...
2020-01-10 14:51:07 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:07 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:07 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:07 WARNING    [database_table_updater.py:mysql_database.python_database_modules.database_table_updater:165] The record (id = b0a36900-ef67-11e9-967c-c326e44c6228) provided already exists in the database! Nothing to do but to exit...
2020-01-10 14:51:07 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:07 WARNING    [database_table_updater.py:mysql_database.python_database_modules.database_table_updater:165] The record (id = c4f98e70-ef67-11e9-967c-c326e44c6228) provided already exists in the database! Nothing to do but to exit...
2020-01-10 14:51:08 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:08 WARNING    [database_table_updater.py:mysql_database.python_database_modules.database_table_updater:165] The record (id = 05e36890-f1cd-11e9-bad3-8bf59b1f7ad1) provided already exists in the database! Nothing to do but to exit...
2020-01-10 14:51:08 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:08 WARNING    [database_table_updater.py:mysql_database.python_database_modules.database_table_updater:165] The record (id = 12f55b10-f1cd-11e9-bad3-8bf59b1f7ad1) provided already exists in the database! Nothing to do but to exit...
2020-01-10 14:51:21 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
2020-01-10 14:51:32 INFO       [utils.py:utils:343] Valid authorization token found. Nothing more to do.
